import Head from "next/head";
import AboutSection from "../components/about-section";
import ContactSection from "../components/contact-section";
import HomeSection from "../components/home-section";
import PortfolioSection from "../components/portfolio-section";

export default function Home() {
  return (
    <>
      <Head>
        <title>AHMDRZK - Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeSection id="home" />
      <AboutSection id="about" />
      <PortfolioSection id="portfolio" />
      <ContactSection id="contact" />
    </>
  );
}
